# Generated by Django 4.2.10 on 2026-06-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_type', models.CharField(choices=[('CODE', 'Code Submission'), ('DIAGRAM', 'Circuit Diagram'), ('REPORT', 'Written Report'), ('VIDEO', 'Video Demo'), ('FILE', 'File Upload')], max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content or code')),
                ('file', models.FileField(blank=True, null=True, upload_to='artifacts/')),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_result', models.JSONField(default=dict, help_text='Validation output')),
                ('score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('feedback', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('expected_output', models.TextField(blank=True)),
                ('test_cases', models.JSONField(default=list)),
                ('xp_reward', models.IntegerField(default=25)),
            ],
            options={
                'ordering': ['mission', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], default='MEDIUM', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('mission_brief', models.TextField(help_text='Detailed mission instructions')),
                ('hints', models.JSONField(default=list, help_text='List of hints')),
                ('required_artifact_type', models.CharField(choices=[('CODE', 'Code Submission'), ('DIAGRAM', 'Circuit Diagram'), ('REPORT', 'Written Report'), ('VIDEO', 'Video Demo'), ('FILE', 'File Upload')], default='CODE', max_length=20)),
                ('validation_script', models.TextField(blank=True, help_text='Python script to validate submission')),
                ('auto_validate', models.BooleanField(default=False)),
                ('xp_reward', models.IntegerField(default=100)),
                ('ether_reward', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('requires_lab', models.BooleanField(default=False)),
                ('associated_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.lab')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
    ]
