# Generated by Django 4.2.10 on 2026-06-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('lab_type', models.CharField(choices=[('VERILOG', 'Verilog HDL'), ('EMBEDDED', 'Embedded Systems'), ('LINUX', 'Linux Terminal'), ('PYTHON', 'Python Environment'), ('GENERAL', 'General Purpose')], default='GENERAL', max_length=20)),
                ('docker_image', models.CharField(help_text="Docker image name, e.g., 'ubuntu:22.04' or 'custom/verilog-env:latest'", max_length=200)),
                ('dockerfile_content', models.TextField(blank=True, help_text='Custom Dockerfile if needed')),
                ('memory_limit', models.CharField(default='512m', help_text="e.g., '512m', '1g'", max_length=10)),
                ('cpu_quota', models.IntegerField(default=50000, help_text='CPU quota in microseconds per 100ms')),
                ('timeout_seconds', models.IntegerField(default=3600, help_text='Auto-terminate after this duration')),
                ('network_enabled', models.BooleanField(default=False, help_text='Enable network access (disabled for security)')),
                ('startup_command', models.TextField(blank=True, help_text='Command to run on container start')),
                ('environment_variables', models.JSONField(default=dict, help_text='Environment variables')),
                ('validation_script', models.TextField(blank=True, help_text='Script to validate lab completion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_id', models.CharField(blank=True, max_length=64)),
                ('container_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('ERROR', 'Error'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('command_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labs.lab')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
