# Generated by Django 4.2.10 on 2026-06-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('ether_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Ether required to unlock this module', max_digits=10)),
                ('completion_xp', models.IntegerField(default=300)),
                ('completion_ether', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives')),
                ('estimated_hours', models.IntegerField(default=5)),
                ('is_locked_by_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='modules.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
