# Generated by Django 4.2.10 on 2026-06-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paths', '0001_initial'),
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='paths.path'),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisite_modules',
            field=models.ManyToManyField(blank=True, to='modules.module'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleunlock',
            unique_together={('user', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('path', 'slug')},
        ),
    ]
