# Generated by Django 4.2.10 on 2026-06-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethertransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ether_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clanwallet',
            name='clan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.clan'),
        ),
        migrations.AddField(
            model_name='clantransaction',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_transactions', to='users.clan'),
        ),
        migrations.AddField(
            model_name='clantransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
